<?php 
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}


/*#############################
###  THEME-BOX-CUSTOM-CLASS ###
#############################*/

/*------------------------------------------------------
//  BODY - POST CLASS
//----------------------------------------------------*/

/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
class Body_Post_Classes_Meta_Box {
	private $screens = array(
		'post',
		'page',
	);
	private $fields = array(
		array(
			'id' => 'body-class',
			'label' => 'Body Class',
			'type' => 'text',
		),
		array(
			'id' => 'post-class',
			'label' => 'Post Class',
			'type' => 'text',
		),
	);

	/**
	 * Class construct method. Adds actions to their respective WordPress hooks.
	 */
	public function __construct() {
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_post' ) );
	}

	/**
	 * Hooks into WordPress' add_meta_boxes function.
	 * Goes through screens (post types) and adds the meta box.
	 */
	public function add_meta_boxes() {
		foreach ( $this->screens as $screen ) {
			add_meta_box(
				'body-post-classes',
				__( 'Body Post Classes', 'advanced-cherry' ),
				array( $this, 'add_meta_box_callback' ),
				$screen,
				'side',
				'default'
			);
		}
	}

	/**
	 * Generates the HTML for the meta box
	 * 
	 * @param object $post WordPress post object
	 */
	public function add_meta_box_callback( $post ) {
		wp_nonce_field( 'body_post_classes_data', 'body_post_classes_nonce' );
		$this->generate_fields( $post );
	}

	/**
	 * Generates the field's HTML for the meta box.
	 */
	public function generate_fields( $post ) {
		$output = '';
		foreach ( $this->fields as $field ) {
			$label = '<label for="' . $field['id'] . '">' . $field['label'] . '</label>';
			$db_value = get_post_meta( $post->ID, 'body_post_classes_' . $field['id'], true );
			switch ( $field['type'] ) {
				default:
					$input = sprintf(
						'<input id="%s" name="%s" type="%s" value="%s">',
						$field['id'],
						$field['id'],
						$field['type'],
						$db_value
					);
			}
			$output .= '<p>' . $label . '<br>' . $input . '</p>';
		}
		echo $output;
	}

	/**
	 * Hooks into WordPress' save_post function
	 */
	public function save_post( $post_id ) {
		if ( ! isset( $_POST['body_post_classes_nonce'] ) )
			return $post_id;

		$nonce = $_POST['body_post_classes_nonce'];
		if ( !wp_verify_nonce( $nonce, 'body_post_classes_data' ) )
			return $post_id;

		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE )
			return $post_id;

		foreach ( $this->fields as $field ) {
			if ( isset( $_POST[ $field['id'] ] ) ) {
				switch ( $field['type'] ) {
					case 'email':
						$_POST[ $field['id'] ] = sanitize_email( $_POST[ $field['id'] ] );
						break;
					case 'text':
						$_POST[ $field['id'] ] = sanitize_text_field( $_POST[ $field['id'] ] );
						break;
				}
				update_post_meta( $post_id, 'body_post_classes_' . $field['id'], $_POST[ $field['id'] ] );
			} else if ( $field['type'] === 'checkbox' ) {
				update_post_meta( $post_id, 'body_post_classes_' . $field['id'], '0' );
			}
		}
	}
}
new Body_Post_Classes_Meta_Box;


/* Filter the <body> class. */
if(!function_exists('_pincuter_metabox_custom_classes_body_class')) {
	add_filter( 'body_class', '_pincuter_metabox_custom_classes_body_class' );
	function _pincuter_metabox_custom_classes_body_class($classes) {
		global $post;
		if ( is_singular() ) {
		$custom_class = get_post_meta( get_queried_object_id(), 'body_post_classes_body-class', true );

		if ( !empty( $custom_class ) )
			$classes[] = sanitize_html_class( $custom_class );
		}

		return $classes;
	}
}


/* Filter the post class. */
if(!function_exists('_pincuter_metabox_custom_classes_post_class')) {
	add_filter( 'post_class', '_pincuter_metabox_custom_classes_post_class', 10, 3 );
	function _pincuter_metabox_custom_classes_post_class( $classes, $class, $post_id ) {

		$custom_class = get_post_meta( $post_id, 'body_post_classes_post-class', true );

		if ( !empty( $custom_class ) )
			$classes[] = sanitize_html_class( $custom_class );

		return $classes;
	}
}



/*##########################
###  BODY AND POST CLASS ###
##########################*/

/* category id in body and post class */
if(!function_exists('category_id_class')) {
	function _pincuter_category_id_class($classes) {
		global $post;
		foreach((get_the_category()) as $category)
			$classes [] = 'cat-' . $category->cat_ID . '-id';
			return $classes;
	}
	add_filter('post_class', '_pincuter_category_id_class');
	add_filter('body_class', '_pincuter_category_id_class');
}
	
	
/* BODY CLASS BROWSER */
add_filter('body_class','_pincuter_custom_browser_body_class');
function _pincuter_custom_browser_body_class($classes = '') {
	global $is_gecko, $is_IE, $is_chrome;

	if($is_gecko) $classes[] = 'gecko';
	elseif($is_chrome) $classes[] = 'chrome';
	elseif($is_IE) $classes[] = 'ie';
	else $classes[] = 'unknown';

	return $classes;
}
	
/* BODY CLASS PAGE/POST NAME */
add_filter( 'body_class', '_pincuter_custom_add_slug_body_class' );
function _pincuter_custom_add_slug_body_class( $classes ) {
	global $post;
	if ( isset( $post ) ) {
		$classes[] = $post->post_type . '-' . $post->post_name;
	}
	return $classes;
}
	
/* add category nicenames in body class */
add_filter( 'body_class', '_pincuter_custom_category_id_class' );
function _pincuter_custom_category_id_class( $classes ) {
	// Only proceed if we're on a single post page
	if ( !is_single() )
		return $classes;
	// Get the categories that are assigned to this post
	$post_categories = get_the_category();
 
	// Loop over each category in the $categories array
	foreach( $post_categories as $current_category ) {
	 
		// Add the current category's slug to the $body_classes array
		$classes[] = 'in-category-'.$current_category->slug; 
	}
	// Finally, return the $body_classes array
	return $classes;
}
	
add_filter( 'body_class', '_pincuter_custom_archive_category_id_class' );
function _pincuter_custom_archive_category_id_class( $classes ) {
	if ( is_category() ) {
		$classes[] = 'archive-category-post';
	}		
	return $classes;
}
	


function body_id( $id = '' ) {
	echo 'id="' . join( ' ', get_body_id( $id ) ) . '"';
}

function get_body_id( $id = '' ) {
	global $wp_query;

	$ids = array();

	$ids[] = 'body';

	if ( ! empty( $id ) ) {
		if ( !is_array( $id ) )
			$id = preg_split( '#\s+#', $id );
		$ids = array_merge( $ids, $id );
	} else {
		$id = array();
	}

	$ids = array_map( 'esc_attr', $ids );

	$ids = apply_filters( 'body_id', $ids, $id );

	return array_unique( $ids );
}